version: '3.9'

services:
  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "3200:3200"
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=dune.settings

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - static_volume:/usr/share/nginx/html/static
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

volumes:
  static_volume: