# Generated by Django 5.1.2 on 2024-12-09 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_photo', models.IntegerField()),
                ('name_first', models.CharField(max_length=255)),
                ('social_net', models.CharField(max_length=45)),
                ('subs', models.CharField(max_length=45)),
                ('tem', models.CharField(max_length=45)),
                ('url_social_net', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicat', models.CharField(default='Отправлено', max_length=45)),
                ('kol', models.IntegerField(default=0)),
                ('blog', models.ManyToManyField(related_name='blog', to='dune_freelance.bloger')),
            ],
        ),
        migrations.CreateModel(
            name='connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.IntegerField(default=0)),
                ('bloger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dune_freelance.bloger')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_konec', models.DateField(default='2024-12-31')),
                ('format', models.CharField(default='Н/Д', max_length=500)),
                ('work_url', models.URLField()),
                ('kol_p', models.IntegerField(default=0)),
                ('photo', models.ImageField(default='imag/5244856793513975742.jpg', upload_to='imag/')),
                ('name_url', models.CharField(max_length=255)),
                ('projects_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apl_blog_us', to='dune_freelance.applications')),
            ],
        ),
        migrations.CreateModel(
            name='date_post_start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_nach', models.DateField()),
                ('apl_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dune_freelance.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Projects_men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('pay', models.IntegerField()),
                ('men_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url_reklam', models.URLField()),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('social_category', models.CharField(max_length=255)),
                ('pay_category', models.CharField(max_length=10)),
                ('stat', models.CharField(max_length=15)),
                ('nums', models.IntegerField()),
                ('us_manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='dune_freelance.projects_men'),
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_res', models.IntegerField()),
                ('id_off', models.IntegerField()),
                ('name_off', models.CharField(max_length=255)),
                ('status_off', models.CharField(max_length=255)),
                ('date_off', models.DateField()),
                ('summ_off', models.IntegerField()),
                ('pst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dune_freelance.posts')),
            ],
        ),
        migrations.CreateModel(
            name='spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_number', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=45)),
                ('us_cpec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
